export const signInDialogTexts = {
    signIn: "Sign In",
    register: "Register",
    email: "Email",
    password: "Password",
    signInForm: "Sign In Form",
    registerForm: "Register Form",
    close: "Close",
    processing: "Processing...",
    validEmail: "Please enter a valid email address.",
    validPassword: "Password must be at least 8 characters.",
    authFailed: "Authentication failed.",
    registrationFailed: "Registration failed.",
    tokenRefreshFailed: "Token refresh failed.",
    apiCallSuccess: "API call successful! Token is valid.",
    apiCallFailed: "API call failed.",
    tokenRefreshed: "Token refreshed. Try again.",
    testApiWithToken: "Test API with Token",
    registrationSuccess: "Registration successful! Please sign in.",
    registerHere: "Register here if you don't have an account",
    alreadyHaveAccount: "I already have an account",
};